version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    depends_on:
      - app
    networks:
      - app-network
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
        - app-network
    container_name: project_app

  db:
    image: mysql:5.7.40
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: stock_tracker
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: '%'
    ports:
      - 8101:3306
    networks:
        - app-network
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db

  npm:
      image: node:latest-alpine
      build:
          context: .
          dockerfile: _docker/app/Dockerfile
      volumes:
          - ./:/var/www/html
      ports:
          - 3000:3000
      networks:
          - app-network
      working_dir: /var/www/html
      container_name: project_npm

networks:
    app-network:
